# Generated by Django 4.2.13 on 2024-05-13 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quorabase', '0002_question_num_vote_down_question_num_vote_up_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='answer_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='question_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
