# Generated by Django 4.2.13 on 2024-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorabase', '0003_alter_answer_options_remove_answer_num_vote_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
